name: Build BannerLogo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Download Agon toolchain v0.16
      run: |
        echo "CWD is: $PWD"
        curl -sL -o agondev.tar.gz https://github.com/AgonPlatform/agondev/releases/download/v0.16/agondev-linux-x64.tar.gz

        file agondev.tar.gz | grep 'gzip compressed data' || {
          echo "ERROR: Downloaded file is not a gzip archive."
          exit 1
        }

        mkdir agondev
        tar -xzf agondev.tar.gz -C agondev

        echo "Toolchain extracted. Contents of agondev/release/bin:"
        ls -l agondev/release/bin

    - name: Build BannerLogo
      run: |
        echo "CWD is: $PWD"
        echo "PATH before update: $PATH"
        export PATH="$PWD/agondev/release/bin:$PATH"
        echo "PATH after update: $PATH"

        echo "Checking agondev-config in PATH:"
        which agondev-config || echo "❌ agondev-config not found"

        echo "Checking if agondev-config exists in bin folder:"
        ls -l agondev/release/bin/agondev-config || echo "❌ agondev-config missing"

        echo "Trying to invoke agondev-config manually:"
        ./agondev/release/bin/agondev-config --version || echo "❌ Failed to run"

        echo "Running make:"
        make

    - name: Upload .bin artifact
      uses: actions/upload-artifact@v4
      with:
        name: bannerlogo-bin
        path: bin/*.bin
