name: Build BannerLogo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Download agondev toolchain
      run: |
        curl -sL -o agondev.tar.gz https://github.com/AgonPlatform/agondev/releases/download/v0.16/agondev-linux-x64.tar.gz
    
        # Confirm it's not an HTML page or error file
        file agondev.tar.gz
    
        # Extract it
        mkdir agondev
        tar -xzf agondev.tar.gz -C agondev
        echo "$PWD/agondev/release/bin" >> $GITHUB_PATH

    - name: Build project
      run: make

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: bannerlogo-bin
        path: bin/*.bin
