name: Build BannerLogo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Download and extract Agon toolchain
      run: |
        echo "CWD is: $PWD"
        curl -sL -o agondev.tar.gz \
          https://github.com/AgonPlatform/agondev/releases/download/v0.16/agondev-linux_x86_64.tar.gz

        file agondev.tar.gz | grep 'gzip compressed data' || {
          echo "ERROR: Downloaded file is not a gzip archive.";
          exit 1;
        }

        tar -xzf agondev.tar.gz

        echo "Contents of ./agondev/release/bin:"
        ls -l ./agondev/release/bin

    - name: Build BannerLogo
      run: |
        export PATH="$PWD/agondev/release/bin:$PATH"
        which agondev-config || echo "❌ agondev-config not found"
        agondev-config --version || echo "❌ Failed to run"

        make

    - name: Upload .bin artifact
      uses: actions/upload-artifact@v4
      with:
        name: bannerlogo-bin
        path: bin/*.bin
