name: Build BannerLogo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Download Agon toolchain v0.16
      run: |
        curl -sL -o agondev.tar.gz https://github.com/AgonPlatform/agondev/releases/download/v0.16/agondev-linux_x86_64.tar.gz
        # Verify it's actually a gzip archive
        file agondev.tar.gz | grep 'gzip compressed data' || {
          echo "ERROR: Downloaded file is not a gzip archive.";
          exit 1;
        }

        # Extract it to ./agondev
        mkdir agondev
        tar -xzf agondev.tar.gz -C agondev

        # Add toolchain binaries to PATH
        export PATH="$PWD/agondev/release/bin:$PATH"

    - name: Build BannerLogo
      run: |
        export PATH="$PWD/agondev/release/bin:$PATH"
        make

    - name: Upload .bin artifact
      uses: actions/upload-artifact@v4
      with:
        name: bannerlogo-bin
        path: bin/*.bin
