name: Build BannerLogo

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Download and extract Agon toolchain
      run: |
        curl -sL -o agondev.tar.gz \
          https://github.com/AgonPlatform/agondev/releases/download/v0.16/agondev-linux_x86_64.tar.gz
        tar -xzf agondev.tar.gz

    - name: Build Agon App
      run: |
        export PATH="$PWD/agondev/release/bin:$PATH"
        make

    - name: Upload .bin artifact
      uses: actions/upload-artifact@v4
      with:
        name: bannerlogo-bin
        path: bin/*.bin
